# get the following AWS information from Compliance viewer:
#
#   cf target -o cf -s toolkit
#   cf env compliance-viewer
#
aws-access-key:
aws-secret-key:
aws-bucket:

# the branch to use for the scripts repo
script-branch: master
# webhook for Slack (described here: https://api.slack.com/incoming-webhooks)
slack-hook:
# which channel should get notified?
slack-channel: '#cloud-gov-highbar'
# name for the slack user
slack-user: concourse
